using System.Collections.Generic;
using UnityEngine;



namespace Rune
{
    /* HTML Color Palette */
    
    public static class ColorPalette
    {
        public static Color GetColor(ColorType type)
        {
            if (!ColorUtility.TryParseHtmlString(_hexCodeLookup[type], out var color)) return Color.black;

            return color;
        }

        public static string GetColorCode(ColorType type)
        {
            return _hexCodeLookup[type];
        }



        public static readonly Dictionary<ColorType, string> _hexCodeLookup = new()
        {
            { ColorType.AliceBlue, "#F0F8FF" },
            { ColorType.AntiqueWhite, "#FAEBD7" },
            { ColorType.Aqua, "#00FFFF" },
            { ColorType.Aquamarine, "#7FFFD4" },
            { ColorType.Azure, "#F0FFFF" },
            { ColorType.Beige, "#F5F5DC" },
            { ColorType.Bisque, "#FFE4C4" },
            { ColorType.Black, "#000000" },
            { ColorType.BlanchedAlmond, "#FFEBCD" },
            { ColorType.Blue, "#0000FF" },
            { ColorType.BlueViolet, "#8A2BE2" },
            { ColorType.Brown, "#A52A2A" },
            { ColorType.BurlyWood, "#DEB887" },
            { ColorType.CadetBlue, "#5F9EA0" },
            { ColorType.Chartreuse, "#7FFF00" },
            { ColorType.Chocolate, "#D2691E" },
            { ColorType.Coral, "#FF7F50" },
            { ColorType.CornflowerBlue, "#6495ED" },
            { ColorType.Cornsilk, "#FFF8DC" },
            { ColorType.Crimson, "#DC143C" },
            { ColorType.Cyan, "#00FFFF" },
            { ColorType.DarkBlue, "#00008B" },
            { ColorType.DarkCyan, "#008B8B" },
            { ColorType.DarkGoldenrod, "#B8860B" },
            { ColorType.DarkGray, "#A9A9A9" },
            { ColorType.DarkGreen, "#006400" },
            { ColorType.DarkKhaki, "#BDB76B" },
            { ColorType.DarkMagenta, "#8B008B" },
            { ColorType.DarkOliveGreen, "#556B2F" },
            { ColorType.DarkOrange, "#FF8C00" },
            { ColorType.DarkOrchid, "#9932CC" },
            { ColorType.DarkRed, "#8B0000" },
            { ColorType.DarkSalmon, "#E9967A" },
            { ColorType.DarkSeaGreen, "#8FBC8F" },
            { ColorType.DarkSlateBlue, "#483D8B" },
            { ColorType.DarkSlateGray, "#2F4F4F" },
            { ColorType.DarkTurquoise, "#00CED1" },
            { ColorType.DarkViolet, "#9400D3" },
            { ColorType.DeepPink, "#FF1493" },
            { ColorType.DeepSkyBlue, "#00BFFF" },
            { ColorType.DimGray, "#696969" },
            { ColorType.DodgerBlue, "#1E90FF" },
            { ColorType.FireBrick, "#B22222" },
            { ColorType.FloralWhite, "#FFFAF0" },
            { ColorType.ForestGreen, "#228B22" },
            { ColorType.Fuchsia, "#FF00FF" },
            { ColorType.Gainsboro, "#DCDCDC" },
            { ColorType.GhostWhite, "#F8F8FF" },
            { ColorType.Gold, "#FFD700" },
            { ColorType.Goldenrod, "#DAA520" },
            { ColorType.Gray, "#808080" },
            { ColorType.Green, "#008000" },
            { ColorType.GreenYellow, "#ADFF2F" },
            { ColorType.Honeydew, "#F0FFF0" },
            { ColorType.HotPink, "#FF69B4" },
            { ColorType.IndianRed, "#CD5C5C" },
            { ColorType.Indigo, "#4B0082" },
            { ColorType.Ivory, "#FFFFF0" },
            { ColorType.Khaki, "#F0E68C" },
            { ColorType.Lavender, "#E6E6FA" },
            { ColorType.LavenderBlush, "#FFF0F5" },
            { ColorType.LawnGreen, "#7CFC00" },
            { ColorType.LemonChiffon, "#FFFACD" },
            { ColorType.LightBlue, "#ADD8E6" },
            { ColorType.LightCoral, "#F08080" },
            { ColorType.LightCyan, "#E0FFFF" },
            { ColorType.LightGoldenrodYellow, "#FAFAD2" },
            { ColorType.LightGray, "#D3D3D3" },
            { ColorType.LightGreen, "#90EE90" },
            { ColorType.LightPink, "#FFB6C1" },
            { ColorType.LightSalmon, "#FFA07A" },
            { ColorType.LightSeaGreen, "#20B2AA" },
            { ColorType.LightSkyBlue, "#87CEFA" },
            { ColorType.LightSlateGray, "#778899" },
            { ColorType.LightSteelBlue, "#B0C4DE" },
            { ColorType.LightYellow, "#FFFFE0" },
            { ColorType.Lime, "#00FF00" },
            { ColorType.LimeGreen, "#32CD32" },
            { ColorType.Linen, "#FAF0E6" },
            { ColorType.Magenta, "#FF00FF" },
            { ColorType.Maroon, "#800000" },
            { ColorType.MediumAquamarine, "#66CDAA" },
            { ColorType.MediumBlue, "#0000CD" },
            { ColorType.MediumOrchid, "#BA55D3" },
            { ColorType.MediumPurple, "#9370DB" },
            { ColorType.MediumSeaGreen, "#3CB371" },
            { ColorType.MediumSlateBlue, "#7B68EE" },
            { ColorType.MediumSpringGreen, "#00FA9A" },
            { ColorType.MediumTurquoise, "#48D1CC" },
            { ColorType.MediumVioletRed, "#C71585" },
            { ColorType.MidnightBlue, "#191970" },
            { ColorType.MintCream, "#F5FFFA" },
            { ColorType.MistyRose, "#FFE4E1" },
            { ColorType.Moccasin, "#FFE4B5" },
            { ColorType.NavajoWhite, "#FFDEAD" },
            { ColorType.Navy, "#000080" },
            { ColorType.OldLace, "#FDF5E6" },
            { ColorType.Olive, "#808000" },
            { ColorType.OliveDrab, "#6B8E23" },
            { ColorType.Orange, "#FFA500" },
            { ColorType.OrangeRed, "#FF4500" },
            { ColorType.Orchid, "#DA70D6" },
            { ColorType.PaleGoldenrod, "#EEE8AA" },
            { ColorType.PaleGreen, "#98FB98" },
            { ColorType.PaleTurquoise, "#AFEEEE" },
            { ColorType.PaleVioletRed, "#DB7093" },
            { ColorType.PapayaWhip, "#FFEFD5" },
            { ColorType.PeachPuff, "#FFDAB9" },
            { ColorType.Peru, "#CD853F" },
            { ColorType.Pink, "#FFC0CB" },
            { ColorType.Plum, "#DDA0DD" },
            { ColorType.PowderBlue, "#B0E0E6" },
            { ColorType.Purple, "#800080" },
            { ColorType.RebeccaPurple, "#663399" },
            { ColorType.Red, "#FF0000" },
            { ColorType.RosyBrown, "#BC8F8F" },
            { ColorType.RoyalBlue, "#4169E1" },
            { ColorType.SaddleBrown, "#8B4513" },
            { ColorType.Salmon, "#FA8072" },
            { ColorType.SandyBrown, "#F4A460" },
            { ColorType.SeaGreen, "#2E8B57" },
            { ColorType.Seashell, "#FFF5EE" },
            { ColorType.Sienna, "#A0522D" },
            { ColorType.Silver, "#C0C0C0" },
            { ColorType.SkyBlue, "#87CEEB" },
            { ColorType.SlateBlue, "#6A5ACD" },
            { ColorType.SlateGray, "#708090" },
            { ColorType.Snow, "#FFFAFA" },
            { ColorType.SpringGreen, "#00FF7F" },
            { ColorType.SteelBlue, "#4682B4" },
            { ColorType.Tan, "#D2B48C" },
            { ColorType.Teal, "#008080" },
            { ColorType.Thistle, "#D8BFD8" },
            { ColorType.Tomato, "#FF6347" },
            { ColorType.Turquoise, "#40E0D0" },
            { ColorType.Violet, "#EE82EE" },
            { ColorType.Wheat, "#F5DEB3" },
            { ColorType.White, "#FFFFFF" },
            { ColorType.WhiteSmoke, "#F5F5F5" },
            { ColorType.Yellow, "#FFFF00" },
            { ColorType.YellowGreen, "#9ACD32" }
        };



        public enum ColorType
        {
            AliceBlue,
            AntiqueWhite,
            Aqua,
            Aquamarine,
            Azure,
            Beige,
            Bisque,
            Black,
            BlanchedAlmond,
            Blue,
            BlueViolet,
            Brown,
            BurlyWood,
            CadetBlue,
            Chartreuse,
            Chocolate,
            Coral,
            CornflowerBlue,
            Cornsilk,
            Crimson,
            Cyan,
            DarkBlue,
            DarkCyan,
            DarkGoldenrod,
            DarkGray,
            DarkGreen,
            DarkKhaki,
            DarkMagenta,
            DarkOliveGreen,
            DarkOrange,
            DarkOrchid,
            DarkRed,
            DarkSalmon,
            DarkSeaGreen,
            DarkSlateBlue,
            DarkSlateGray,
            DarkTurquoise,
            DarkViolet,
            DeepPink,
            DeepSkyBlue,
            DimGray,
            DodgerBlue,
            FireBrick,
            FloralWhite,
            ForestGreen,
            Fuchsia,
            Gainsboro,
            GhostWhite,
            Gold,
            Goldenrod,
            Gray,
            Green,
            GreenYellow,
            Honeydew,
            HotPink,
            IndianRed,
            Indigo,
            Ivory,
            Khaki,
            Lavender,
            LavenderBlush,
            LawnGreen,
            LemonChiffon,
            LightBlue,
            LightCoral,
            LightCyan,
            LightGoldenrodYellow,
            LightGray,
            LightGreen,
            LightPink,
            LightSalmon,
            LightSeaGreen,
            LightSkyBlue,
            LightSlateGray,
            LightSteelBlue,
            LightYellow,
            Lime,
            LimeGreen,
            Linen,
            Magenta,
            Maroon,
            MediumAquamarine,
            MediumBlue,
            MediumOrchid,
            MediumPurple,
            MediumSeaGreen,
            MediumSlateBlue,
            MediumSpringGreen,
            MediumTurquoise,
            MediumVioletRed,
            MidnightBlue,
            MintCream,
            MistyRose,
            Moccasin,
            NavajoWhite,
            Navy,
            OldLace,
            Olive,
            OliveDrab,
            Orange,
            OrangeRed,
            Orchid,
            PaleGoldenrod,
            PaleGreen,
            PaleTurquoise,
            PaleVioletRed,
            PapayaWhip,
            PeachPuff,
            Peru,
            Pink,
            Plum,
            PowderBlue,
            Purple,
            RebeccaPurple,
            Red,
            RosyBrown,
            RoyalBlue,
            SaddleBrown,
            Salmon,
            SandyBrown,
            SeaGreen,
            Seashell,
            Sienna,
            Silver,
            SkyBlue,
            SlateBlue,
            SlateGray,
            Snow,
            SpringGreen,
            SteelBlue,
            Tan,
            Teal,
            Thistle,
            Tomato,
            Turquoise,
            Violet,
            Wheat,
            White,
            WhiteSmoke,
            Yellow,
            YellowGreen,
        }

    }
}